global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'order-service-cluster'
    environment: 'development'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Node Exporter - métricas do sistema
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  # Spring Boot Actuator - métricas da aplicação
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'order-service'
          profile: 'order-consumer'

  # MongoDB Exporter (caso queira adicionar)
  # - job_name: 'mongodb'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']

  # RabbitMQ (já expõe métricas Prometheus nativamente)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
        labels:
          service: 'rabbitmq'
